### ISSUE TITLE
[Feature Request] Classes / Output File

### ISSUE THREAD

**Issue by ClutchReboot** [josemlwdf/1nj3ct0r#1]
1nj3ct0r is excellent and has helped me a couple times. If you're bored or looking for improvements here's a couple things I can think of:

1. Incorporate classes / comments to help organize the code.
2. Add an option to specify an output file to write to. There's a great library called [argsparse](https://docs.python.org/3/library/argparse.html) that could help keep options organized.

If you're welcoming forks, I can help with some changes. Great job and keep at it!

**Comment by josemlwdf** [comment]
I do not really have the time to add features at this moment. Feel free to add them.
